### ISSUE TITLE
Handle long urls and notify users appropriately

### ISSUE THREAD

**Issue by Enngage** [Enngage/kentico-cloud-js#28]

**Comment by Enngage** [comment]
There is no universal value for maximum number of characters in URL and SDK should not dictate this either. Developers using SDK will have to make sure their URLs are valid for their own purposes.

**Comment by petrsvihlik** [comment]
How about this https://github.com/Kentico/delivery-sdk-net/blob/72faab0717cbf0959f3c38cef70987c526e1f470/KenticoCloud.Delivery/DeliveryEndpointUrlBuilder.cs#L9?

**Comment by Enngage** [comment]
I'm pretty sure thats invalid and has no real purpose (other than maybe the max. string length in .NET?). I would recommend removing that from .NET SDK. For maximum chars in URL I checked mainly the answers from SO here https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers)

**Comment by petrsvihlik** [comment]
The other option would be to set it to the lowest value - 2k... But you are probably right it's not worth implementing as there is no standard.
