### ISSUE TITLE
Improve pagination in the DeliveryItemListingResponse

### ISSUE THREAD

**Issue by JanLenoch** [Enngage/kentico-cloud-js#5]
As part of the DeliveryItemListingResponse object, the Pagination.NextPageUrl property provides a reference to getting the next page data.

The Delivery client (the "items" method) should be able to get the next page data, either using the NextPageUrl, or something more appropriate.

**Comment by Enngage** [comment]
Will take look, thanks!

**Comment by JanLenoch** [comment]
The value added by such a function (as opposed to just a URL property) would be rather minimal.
