### ISSUE TITLE
Missing links property in RichTextField

### ISSUE THREAD

**Issue by Simply007** [Enngage/kentico-cloud-js#53]
RichTextField contained property `links` in previous versions.

In the sample site for react code relied on that property. I have made a pull request with the workaround.
* https://github.com/Kentico/cloud-sample-app-react/pull/82

Consider implementing the property back (if so please raise the issue to revert the commit https://github.com/Kentico/cloud-sample-app-react/pull/82/commits/3cb71d28a099e2ac2c366b580dafc64970626fae)

**Comment by Enngage** [comment]
Added to `4.0.2`
