### ISSUE TITLE
Generators link

### ISSUE THREAD

**Issue by petrsvihlik** [Enngage/kentico-cloud-js#54]
@Enngage please agree with our documentation team that the link leading to the generator utility gets changed in the official docu. Ideally, create an issue in the CTC backlog.

https://developer.kenticocloud.com/docs/javascript

**Comment by Enngage** [comment]
Note added to existing task for renaming SDK. Should be fixed soon.

**Comment by Enngage** [comment]
Fixed by TWs :)
