### ISSUE TITLE
Problems with filtering

### ISSUE THREAD

**Issue by rubenberendsen** [Enngage/kentico-cloud-js#59]
Hi,

I want to get data from kentico cloud en filter it by a category with a ContainsFilter.

![example-kc-jssdk](https://user-images.githubusercontent.com/38040580/42038311-f20ee9ac-7aea-11e8-8aaa-07cb7c767efb.png)
This is my code

If i check the URL in the console.log than i get this URL: 
https://deliver.kenticocloud.com/3e6bfb89-fc83-01fb-256c-7d3da2d9bd64/items?system.type=update&elements.updates[contains]=&depth=999

The tag 'marketing' is missing..

**Comment by petrsvihlik** [comment]
Thx @kentico-anthonym! Would you care to send a pull request with updated docs (if you have time to spare)?

**Comment by Simply007** [comment]
@rubenberendsen 
It is exactly as @kentico-anthonym says.

Here is a test covering contains filter functionality:
* https://github.com/Enngage/kentico-cloud-js/blob/master/packages/delivery/test-browser/isolated-tests/url/item-filters.ts#L89

**Comment by Enngage** [comment]
Docs updated (https://github.com/Enngage/kentico-cloud-js/commit/6ee960179999d2c3b6b82c1c85d3477137a6036f), closing
