### ISSUE TITLE
Rename modular content to linked items

### ISSUE THREAD

**Issue by petrsvihlik** [Enngage/kentico-cloud-js#72]
Based on our vision regarding content items, we have to rename "Modular content element" to "Linked items element". From the Delivery SDK's point of view, it means that we are going to rename everything that contains "modularContent" to "linkedItems".

Checklist:
- [x] updated all members (methods/properties/classes/...)
- [x] updated .MD files
- [x] updated tests
- [x] updated github wiki

Keep in mind, that the Delivery API responses will remain the same. They'll still contain "modular_content".

Example implementation: https://github.com/Kentico/delivery-sdk-net/pull/130

Notes:
- this will result in a breaking change because of changes in public members -> [major version number has to be increased](https://semver.org/)
- plan your release so that the changes go live on 2018-10-03 and onwards.

**Comment by Enngage** [comment]
Done, will be released as part of `5.0.0`
