### ISSUE TITLE
Generating strongly typed models fails with Deliver API Secure access enabled

### ISSUE THREAD

**Issue by matus666** [Enngage/kentico-cloud-js#73]
### Motivation

It would be useful to add this as customers are using it/requiring it.

### Additional context

https://www.npmjs.com/package/kentico-cloud-model-generator-utility
intercom convo: https://app.intercom.io/a/apps/e42kus8l/inbox/inbox/1380351/conversations/18749390876

**Comment by Enngage** [comment]
Released in `1.1.0`. You can use `secureAccessKey` in generator arguments.
