### ISSUE TITLE
Do not remove the array of modular (linked) item codenames

### ISSUE THREAD

**Issue by JanLenoch** [Enngage/kentico-cloud-js#78]
### Motivation

The SDK uses [rich text resolvers](https://github.com/Enngage/kentico-cloud-js/blob/master/doc/delivery.md#resolving-linked-items-in-rich-text-fields) to transform modular (linked) item references found in rich text elements into HTML (or other output format). This is great but the SDK also removes the property that holds the array of codenames from the original response.

In Gatsby, the internal GraphQL store abstracts from presentation and the codenames of items is exactly what is needed to [build the standard relationships](https://github.com/Kentico/gatsby-source-kentico-cloud/blob/master/src/normalize.js#L210) among nodes. In order for the Gatsby source plugin to work, I have to [refill](https://github.com/Kentico/gatsby-source-kentico-cloud/blob/master/src/normalize.js#L130) the missing `modular_content` array from the `debug` part of the response.

### Proposed solution

If possible, do not strip the `modular_content` array from the rich text element JavaScript objects.

**Comment by Enngage** [comment]
Available in https://www.npmjs.com/package/kentico-cloud-delivery/v/5.0.0-beta.6
